# This is the "main" Snakefile, from which all subtasks are launched. 
# The config file is read in, and the "localrules" line specifies which rules
# should not be run on the cluster (because they don't need that much resources)
# The rule "filtered" is essentially the master rule, in which all final output
# files are specified (as input for it, hence there's no output specified)

import re

configfile: "config.yml"
localrules: all, index_bam, index_reference, retain_list

rule all:
    input:
        expand('{vcf_dir}/genome.IF-GF-MM2-RM.vcf.gz', vcf_dir = config["vcf_dir"]),
        expand('{vcf_dir}/genome.IF-GF-MM2-RM.vcf.gz.csi', vcf_dir = config["vcf_dir"])

include: "rules/scripts.smk"

include: "rules/read_mapping.smk"

include: "rules/call.smk"

include: "rules/filter.smk"