name: LR-variant-calling
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python
  - bioconda::snakemake
  - bioconda::bcftools
  - bioconda::snakemake-executor-plugin-slurm
  - datamash
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - bamtools=2.5.2
  - bedtools=2.30.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - giflib=5.2.2
  - graphite2=1.3.13
  - gsl=2.7
  - harfbuzz=6.0.0
  - htslib=1.16
  - icu=72.1
  - jpeg=9e
  - k8=0.2.5
  - keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=7.85.0
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=12.2.0
  - libiconv=1.17
  - libnghttp2=1.47.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libzlib=1.2.13
  - mashmap=3.0.6
  - meryl=1.3
  - minimap2=2.26
  - ncurses=6.3
  - openblas=0.3.27
  - openjdk=17.0.3
  - pcre2=10.43
  - picard=1.141
  - pixman=0.43.2
  - pthread-stubs=0.4
  - samtools=1.16.1
  - winnowmap=2.03
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13